name: tsub
description: A set of stub files
version: 1.0.0
homepage: https://github.com/tyrcord/tsub

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  pedantic: ^1.11.1
  test: ^1.21.4
  dart_code_metrics: ^4.19.1
